language: python
notifications:
  email: false
python:
  - "2.7"
  - "3.6"
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pip install progressbar2
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=xtal
after_success:
  - coveralls