language: python
python:
  - "2.7"
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pip install progressbar2
  - pip install coveralls
script:
  - pytest --cov=xtal
after_success:
  - coveralls